/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleKelompok2;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String halo() {
        return "Halo";
    }
    public static void main(String[] args) {
        System.out.println(new App().halo());
    }
}
